http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:3000
  session_ttl: 720h
users:
  - name: root
    password: $2y$10$dwn0hTYoECQMZETBErGlzOId2VANOVsPHsuH13TM/8KnysM5Dh/ve
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: zh-cn
theme: auto
dns:
  bind_hosts:
    - 0.0.0.0
  port: 5335
  anonymize_client_ip: false
  ratelimit: 0
  ratelimit_subnet_len_ipv4: 24
  ratelimit_subnet_len_ipv6: 56
  ratelimit_whitelist: []
  refuse_any: false
  upstream_dns:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - 127.0.0.1:7874
  upstream_dns_file: ""
  bootstrap_dns:
    - 223.5.5.5
    - 119.29.29.29
  fallback_dns: []
  upstream_mode: parallel
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: true
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  bootstrap_prefer_ipv6: false
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
  serve_plain_dns: true
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
querylog:
  ignored: []
  interval: 24h
  size_memory: 1000
  enabled: true
  file_enabled: true
statistics:
  ignored: []
  interval: 720h
  enabled: true
filters:
  - enabled: true
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard DNS filter
    id: 1228750870
  - enabled: true
    url: http://sub.adtchrome.com/adt-chinalist-easylist.txt
    name: 广告终结者使用的拦截规则，基于ChinaList+EasyList修正维护
    id: 139789181
  - enabled: true
    url: https://easylist-downloads.adblockplus.org/easylist.txt
    name: EasyList-去除国际网页中大多数广告，包括不需要的框架、图像和对象
    id: 139789112
  - enabled: true
    url: https://easylist-downloads.adblockplus.org/easylistchina.txt
    name: EasyList China-EasyList针对国内的补充规则
    id: 139789121
  - enabled: true
    url: https://anti-ad.net/adguard.txt
    name: anti-AD命中率最高列表
    id: 139789122
  - enabled: true
    url: https://raw.iqiq.io/banbendalao/ADgk/master/ADgk.txt
    name: ADgk去广告easylistchina补充规则
    id: 139789131
  - enabled: true
    url: https://raw.iqiq.io/banbendalao/ADgk/master/kill-baidu-ad.txt
    name: ADgk百度广告过滤
    id: 139789133
  - enabled: false
    url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext
    name: Peter Lowe’s Ad and tracking server list​
    id: 139789152
  - enabled: false
    url: https://easylist.to/easylist/fanboy-social.txt
    name: Fanboy's Social Blocking List
    id: 139789153
  - enabled: false
    url: https://easylist.to/easylist/fanboy-annoyance.txt
    name: Fanboy's Annoyance List
    id: 139789154
  - enabled: false
    url: https://secure.fanboy.co.nz/fanboy-cookiemonster.txt
    name: EasyList Cookie List
    id: 139789155
  - enabled: false
    url: https://fanboy.co.nz/fanboy-antifacebook.txt
    name: Anti-Facebook List
    id: 139789161
  - enabled: false
    url: https://filters.adtidy.org/extension/ublock/filters/14.txt
    name: AdGuard Annoyances filter
    id: 139789162
  - enabled: false
    url: https://www.fanboy.co.nz/enhancedstats.txt
    name: Fanboy's Enhanced Tracking List
    id: 139789164
  - enabled: false
    url: https://filters.adtidy.org/extension/ublock/filters/3.txt
    name: AdGuard Tracking Protection filter
    id: 139789165
  - enabled: false
    url: https://easylist.to/easylist/easylist.txt
    name: EasyList
    id: 139789171
  - enabled: false
    url: https://filters.adtidy.org/extension/ublock/filters/11.txt
    name: AdGuard Mobile Ads filter
    id: 139789172
  - enabled: false
    url: https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt
    name: AdGuard Base filter
    id: 139789173
  - enabled: false
    url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
    name: Adblock Warning Removal List
    id: 139789174
  - enabled: false
    url: https://fanboy.co.nz/fanboy-problematic-sites.txt
    name: Fanboy's problematic-sites
    id: 139789175
  - enabled: false
    url: https://adaway.org/hosts.txt
    name: Adaway HOST
    id: 139789187
whitelist_filters: []
user_rules: []
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
filtering:
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_services:
    schedule:
      time_zone: UTC
    ids: []
  protection_disabled_until: null
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    google: true
    pixabay: true
    yandex: true
    youtube: true
  blocking_mode: default
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  rewrites: []
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  filters_update_interval: 24
  blocked_response_ttl: 60
  filtering_enabled: true
  parental_enabled: false
  safebrowsing_enabled: false
  protection_enabled: true
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log:
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 28
